### ISSUE TITLE
Game crashes when generating/loading a superflat world with the 'The Void' preset.

### ISSUE THREAD

**Issue by PapierZylinder** [MSpaceDev/MonsterTotems#1]
#### Issue Description:
The game crashes when you try to generate a superflat world with the void preset. That only happens when you choose the void preset, every other preset seems to be fine and does not crash during loading.

#### What happens:
When you generate or enter a superflat world with the void preset the game crashes.

#### What you expected to happen:
When you generate or enter a superflat world with the void preset the game should not crash.

#### Steps to reproduce:
1.Start the game.
2.Choose to generate or enter a superflat world with the 'The Void' preset
3.Generate the world
4.See how the game crashes.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- MonsterTotems-1.12.2-2.0.0.1

#### Your most recent log file where the issue was present: 

https://pastebin.com/FMGHCadx

**Comment by MSpaceDev** [comment]
Will look into it soon. I'm pretty sure it has something to do with dimension IDs.

**Comment by MSpaceDev** [comment]
This has been solved in **Monster-Totems-1.12.2-2.0.1.2**. It will be released later today.
