### ISSUE TITLE
[Suggestion] Visible Radius Box toggle?

### ISSUE THREAD

**Issue by SonicX8000** [MSpaceDev/MonsterTotems#6]
I was wondering if by right-clicking a totem base it would show you it's radius box so you'll know the range that the totem gives off.

Trying to safe-proof an area with totems but I feel like I may of made too many of them since I don't know the exact range that go... well... I know that there's a configurable range but a visual would be nice to have.

If the config option is set so it goes all the way from bedrock to world height, then the box will show that alongside the radius. Would also help when it's a cylinder radius instead of a cube/square.

**Comment by MSpaceDev** [comment]
Good suggestion. However, I am no longer maintaining this project :) Thanks for using my mod

**Comment by SonicX8000** [comment]
Aw... alright
